/*
  ==============================================================================

	This file was auto-generated by the Introjucer!

	It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "GonioPoints.h"
#include <vector>
#include "CustomDrawing.h"
#include "MainLayout.h"
#include "GoniometerControl.h"
#include "SpectrometerControl.h"
#include "TomatlLookAndFeel.h"
//==============================================================================
/**
*/

class AdmvAudioProcessorEditor  : public AudioProcessorEditor, public Timer
{
private:
	
	GoniometerControl mGonio;
	MainLayout mLayout;
	SpectrometerControl mSpectrometer;
	TomatlLookAndFeel mLookAndFeel;

	void addComponent(int x, int y, Component& ctrl)
	{
		addAndMakeVisible(ctrl);
		ctrl.setTopLeftPosition(x, y);
	}

public:
	AdmvAudioProcessorEditor (AdmvAudioProcessor* ownerFilter)
		: AudioProcessorEditor(ownerFilter), mGonio(ownerFilter), mSpectrometer(ownerFilter)
	{
		LookAndFeel::setDefaultLookAndFeel(&mLookAndFeel);
		setSize(mLayout.getWidth(), mLayout.getHeight());
		addComponent(0, 0, mLayout);
		addComponent(0, 0, mGonio);
		addComponent(mGonio.getWidth(), 0, mSpectrometer);

		startTimer(1000. / 25.);
	}

	~AdmvAudioProcessorEditor()
	{
	}

	virtual void timerCallback()
	{
		mGonio.repaint();
		mSpectrometer.repaint();
	}

	static float logDecay(float alpha)
	{
		return std::max(0.01, alpha - std::log(alpha * 255) / 255 * 2.5) - 0.01;
	}
	//==============================================================================
	// This is just a standard Juce paint method...
	void paint(Graphics& g)
	{

	}
};


#endif  // PLUGINEDITOR_H_INCLUDED
